// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'left': string;
  'regionCenter': string;
  'regionNorth': string;
  'regionWest': string;
  'todoListContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
